import { EB_Garamond } from "next/font/google";
import "./globals.css";
import { FrameInit } from "@/components/FrameInit";

const garamond = EB_Garamond({
  variable: '--font-garamond',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'], // adjust based on your needs
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`{garamond.variable}`}>
        {children}
        <FrameInit />
      </body>
    </html>
  );
}
